### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'as_matrix'

### ISSUE THREAD

**Issue by yechao1995** [minepy/mictools#6] opened 2020-02-05 04:11 UTC
when I run ''mictools null $X $ODIR/null_dist.txt''but encountered the following error:
AttributeError: 'DataFrame' object has no attribute 'as_matrix'
Any suggestions?

**Comment by davidealbanese** [comment] 2020-02-05 10:55
I think the problem is the "statsmodels" package. Please report the complete error message.

**Comment by yechao1995** [comment] 2020-02-06 01:53
yc@yc-virtual-machine:~/mictools-master$ mictools null $X $ODIR/null_dist.txt
Traceback (most recent call last):
  File "/home/yc/.local/bin/mictools", line 7, in <module>
    from scripts.mictools_cmd import cli
  File "/home/yc/.local/lib/python2.7/site-packages/scripts/mictools_cmd.py", line 27, in <module>
    import mictools.pval
  File "/home/yc/.local/lib/python2.7/site-packages/mictools/pval.py", line 34, in <module>
    import mictools.mtest
  File "/home/yc/.local/lib/python2.7/site-packages/mictools/mtest.py", line 26, in <module>
    import statsmodels.stats.multitest
  File "/home/yc/.local/lib/python2.7/site-packages/statsmodels/stats/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/home/yc/.local/lib/python2.7/site-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/home/yc/.local/lib/python2.7/site-packages/statsmodels/tools/tools.py", line 8, in <module>
    from statsmodels.compat.python import lzip, lmap
  File "/home/yc/.local/lib/python2.7/site-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/home/yc/.local/lib/python2.7/site-packages/statsmodels/tools/_testing.py", line 11, in <module>
    from statsmodels.compat.pandas import assert_equal
  File "/home/yc/.local/lib/python2.7/site-packages/statsmodels/compat/pandas.py", line 4, in <module>
    import numpy as np
  File "/home/yc/.local/lib/python2.7/site-packages/statsmodels/compat/numpy.py", line 46, in <module>
    NP_LT_114 = LooseVersion(np.__version__) < LooseVersion('1.14')
AttributeError: 'module' object has no attribute '__version__'

**Comment by yechao1995** [comment] 2020-02-06 12:01
yc@yc-virtual-machine:~/mictools-master/examples$ mictools null $X $ODIR/null_dist.txt
X: 26 variables
Samples per class:
* None: 142
Traceback (most recent call last):
  File "/usr/local/bin/mictools", line 11, in <module>
    load_entry_point('mictools==1.0.1', 'console_scripts', 'mictools')()
  File "/home/yc/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/yc/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/yc/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yc/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yc/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mictools-1.0.1-py3.6.egg/scripts/mictools_cmd.py", line 101, in null
  File "/usr/local/lib/python3.6/dist-packages/mictools-1.0.1-py3.6.egg/mictools/null.py", line 134, in null_cmd
  File "/usr/local/lib/python3.6/dist-packages/mictools-1.0.1-py3.6.egg/mictools/null.py", line 100, in compute_null
  File "/usr/local/lib/python3.6/dist-packages/mictools-1.0.1-py3.6.egg/mictools/null.py", line 40, in compute_null_oneclass
  File "/home/yc/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'

**Comment by davidealbanese** [comment] 2020-02-06 15:04
Fixed in version 1.1.2

**Closed as completed by davidealbanese** 2020-02-06 15:04 UTC

**Comment by yechao1995** [comment] 2020-02-06 15:55
succeed,thank you very much.
